Document: wii-u-gc-adapter
Title: Debian wii-u-gc-adapter Manual
Author: <insert document author here>
Abstract: This manual describes what wii-u-gc-adapter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wii-u-gc-adapter/wii-u-gc-adapter.sgml.gz

Format: postscript
Files: /usr/share/doc/wii-u-gc-adapter/wii-u-gc-adapter.ps.gz

Format: text
Files: /usr/share/doc/wii-u-gc-adapter/wii-u-gc-adapter.text.gz

Format: HTML
Index: /usr/share/doc/wii-u-gc-adapter/html/index.html
Files: /usr/share/doc/wii-u-gc-adapter/html/*.html
